name: fsfp
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - pytorch
  - pytorch-cuda=11.8
  - torchvision
  - transformers>=4.29.2
  - peft>=0.4.0
  - scipy>=1.10.1
  - scikit-learn>=1.3.0
  - fastapi
  - uvicorn
  - python-multipart
